// Generated by CoffeeScript 1.9.0
(function() {
  var exec;

  exec = require("child_process").exec;

  exec("npm install -g coffee-script");

  exec("npm install -g mocha");

  process.exit;

}).call(this);
