// Generated by CoffeeScript 1.9.1
(function() {
  var Animal, Customer, animal;

  Customer = (function() {
    Customer.prototype.name = "unknown";

    function Customer(name) {
      this.name = name;
    }

    Customer.prototype.sayName = function() {
      return console.log("my name is " + this.name);
    };

    return Customer;

  })();

  Animal = (function() {
    function Animal() {}

    Animal.prototype.price = 5;

    Animal.prototype.sell = function(customer) {
      return console.log(customer.name);
    };

    return Animal;

  })();

  animal = new Animal;

  animal.sell(new Customer("Frank"));

  animal.sell(new Customer("Bob"));

}).call(this);
