// Generated by CoffeeScript 1.9.0
(function() {
  describe("Customer Basic", function() {
    var Customer;
    Customer = require("../src/models/characters").Customer;
    return it("should set a name", function() {
      var customer;
      customer = new Customer("Chris");
      return expect(customer.name).toBe("Chris");
    });
  });

}).call(this);
