// Generated by CoffeeScript 1.9.0
(function() {
  var Customer;

  Customer = require("../src/models/characters").Customer;

  describe("Customer Class", function() {
    it("should set a name", function() {
      var props, sut;
      props = {
        firstName: "Chris",
        lastName: "Mumford"
      };
      sut = new Customer(props);
      return expect(sut.firstName).toBe("Chris");
    });
    it("should set a wallet value", function() {
      var props, sut;
      props = {
        wallet: 22.34
      };
      sut = new Customer(props);
      return expect(sut.wallet).toEqual(22.34);
    });
    return it("should set wallet value as float", function() {
      var props, sut;
      props = {
        wallet: 10.2
      };
      sut = new Customer(props);
      return expect(sut.wallet).toBe(10.20);
    });
  });

}).call(this);
