// Generated by CoffeeScript 1.9.0
(function() {
  var Animal, Customer, exports;

  Animal = (function() {
    function Animal() {}

    Animal.prototype.price = 5;

    Animal.prototype.sell = function(customer) {
      return console.log(customer.name);
    };

    return Animal;

  })();

  Customer = (function() {
    function Customer(options) {
      var key, val;
      if (options == null) {
        options = {};
      }
      for (key in options) {
        val = options[key];
        this[key] = val;
      }
    }

    Customer.prototype.sayName = function() {
      return console.log("My name is " + this.name);
    };

    return Customer;

  })();

  exports = this;

  exports.Animal = Animal;

  exports.Customer = Customer;

}).call(this);
